[tool.poetry]
name = "til24-nlp"
version = "0.1.0"
description = "template for python api server"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
rich = "^13.7.1"
fastapi = { extras = ["all"], version = "^0.111.0" }
python-dotenv = "^1.0.1"
instructor = "^1.2.6"

[tool.poetry.group.dev.dependencies]
ruff = "*"
poethepoet = "*"
rouge-score = "^0.1.2"
pandas = "^2.2.2"
requests = "^2.31.0"

[tool.poe.tasks]
dev = "python dev.py"
prod = "docker run --rm --gpus all -p 5002:5002 nyanplan3-nlp"
test = "python eval/test_nlp.py"

[tool.poe.tasks.build]
cmd = "docker build -f Dockerfile . -t nyanplan3-nlp:latest -t nyanplan3-nlp:${tag}"
args = [{ name = "tag", positional = true, required = true }]

[tool.ruff.lint]
select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
